package aero.flyfun.forms.data

import aero.flyfun.forms.logic.AirportSearch
import aero.flyfun.forms.logic.AirportSummary
import aero.flyfun.forms.logic.AirportTimezones
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.io.File

/** The airport database, as the screens use it: an interface so a ViewModel can do without one. */
interface Airports {
    suspend fun search(needle: String): List<AirportSummary>
    suspend fun airport(icao: String): AirportSummary?
    suspend fun timeZone(icao: String): String?
}

/**
 * The bundled airport database (`airports.db`, copied into assets at build
 * time) and the airport time zone table beside it. Port of iOS
 * `AirportDatabase` + `AirportTimezoneCache`, minus the geocoding: the zones
 * come from `airport_timezones.csv`, generated by `scripts/airport_timezones.py`.
 *
 * SQLite cannot open a file inside the APK, so the database is copied to
 * no-backup storage once per build of the app. Read-only; nothing here is
 * the pilot's data.
 */
class AirportDatabase private constructor(private val context: Context) : Airports {

    private val mutex = Mutex()
    private var db: SQLiteDatabase? = null
    private var zones: Map<String, String>? = null

    /** Airports matching [needle] by code, name or city, best first. Empty until there is something to search. */
    override suspend fun search(needle: String): List<AirportSummary> = search(needle, 20)

    suspend fun search(needle: String, limit: Int): List<AirportSummary> {
        val n = AirportSearch.normalise(needle)
        if (n.isEmpty()) return emptyList()
        val database = open() ?: return emptyList()
        return withContext(Dispatchers.IO) {
            val like = "%${n.replace("%", "").replace("_", "")}%"
            val candidates = database.rawQuery(
                """
                SELECT $COLUMNS FROM airports
                WHERE icao_code LIKE ? OR iata_code = ? OR name LIKE ? OR municipality LIKE ?
                LIMIT 400
                """.trimIndent(),
                arrayOf("${n.uppercase()}%", n.uppercase(), like, like),
            ).use { cursor -> buildList { while (cursor.moveToNext()) add(cursor.toSummary()) } }
            AirportSearch.rank(n, candidates, limit)
        }
    }

    /** One airport by its ICAO code, or null when it is not in the database. */
    override suspend fun airport(icao: String): AirportSummary? {
        if (icao.isBlank()) return null
        val database = open() ?: return null
        return withContext(Dispatchers.IO) {
            database.rawQuery("SELECT $COLUMNS FROM airports WHERE icao_code = ?", arrayOf(icao.uppercase()))
                .use { if (it.moveToFirst()) it.toSummary() else null }
        }
    }

    /** The airport's IANA zone, or null for one the table does not know. */
    override suspend fun timeZone(icao: String): String? {
        if (icao.isBlank()) return null
        val table = zones ?: withContext(Dispatchers.IO) {
            runCatching {
                context.assets.open(ZONES_ASSET).bufferedReader().use { AirportTimezones.parse(it.readText()) }
            }.getOrDefault(emptyMap())
        }.also { zones = it }
        return table[icao.uppercase()]
    }

    private suspend fun open(): SQLiteDatabase? = mutex.withLock {
        db ?: withContext(Dispatchers.IO) {
            runCatching {
                val file = copied()
                SQLiteDatabase.openDatabase(file.path, null, SQLiteDatabase.OPEN_READONLY)
            }.getOrNull()
        }.also { db = it }
    }

    /**
     * The asset as a file, copied again when the app is updated: the file is
     * named after the app's install time, so a new build's database replaces
     * the last one's.
     */
    private fun copied(): File {
        val stamp = runCatching {
            context.packageManager.getPackageInfo(context.packageName, 0).lastUpdateTime
        }.getOrDefault(0L)
        val dir = File(context.noBackupFilesDir, "airports").apply { mkdirs() }
        val file = File(dir, "airports-$stamp.db")
        if (!file.exists()) {
            dir.listFiles()?.forEach { it.delete() }
            val partial = File(dir, "${file.name}.part")
            context.assets.open(DB_ASSET).use { input -> partial.outputStream().use { input.copyTo(it) } }
            partial.renameTo(file)
        }
        return file
    }

    private fun android.database.Cursor.toSummary() = AirportSummary(
        icao = getString(0).orEmpty(),
        name = getString(1).orEmpty(),
        city = getString(2).orEmpty(),
        country = getString(3).orEmpty(),
        type = getString(4).orEmpty(),
        iata = getString(5)?.takeIf { it.isNotBlank() },
    )

    companion object {
        private const val DB_ASSET = "airports.db"
        private const val ZONES_ASSET = "airport_timezones.csv"
        private const val COLUMNS = "icao_code, name, municipality, iso_country, type, iata_code"

        @Volatile
        private var instance: AirportDatabase? = null

        fun get(context: Context): AirportDatabase =
            instance ?: synchronized(this) {
                instance ?: AirportDatabase(context.applicationContext).also { instance = it }
            }
    }
}
