package aero.flyfun.forms.logic

import java.time.Instant

/** One airport from the bundled `airports.db`, as a picker shows it. */
data class AirportSummary(
    val icao: String,
    val name: String = "",
    val city: String = "",
    val country: String = "",
    /** `large_airport`, `medium_airport` or `small_airport`. */
    val type: String = "",
    val iata: String? = null,
)

/**
 * Ranking for the airport pickers, standing in for RZFlight's
 * `KnownAirports.rankedSearch` on iOS: code matches before name matches,
 * and among equals the bigger airport first.
 */
object AirportSearch {

    /** The words the database is queried with: the needle, trimmed, as typed. */
    fun normalise(needle: String): String = needle.trim()

    fun rank(needle: String, candidates: List<AirportSummary>, limit: Int = 20): List<AirportSummary> {
        val n = normalise(needle).uppercase()
        if (n.isEmpty()) return emptyList()
        return candidates
            .mapNotNull { airport -> score(n, airport)?.let { airport to it } }
            .sortedWith(
                compareBy<Pair<AirportSummary, Int>> { it.second }
                    .thenBy { size(it.first.type) }
                    .thenBy { it.first.icao },
            )
            .take(limit)
            .map { it.first }
    }

    /** Lower is better; null is no match. */
    private fun score(n: String, airport: AirportSummary): Int? {
        val icao = airport.icao.uppercase()
        val name = airport.name.uppercase()
        val city = airport.city.uppercase()
        return when {
            icao == n -> 0
            airport.iata?.uppercase() == n -> 1
            icao.startsWith(n) -> 2
            name.startsWith(n) || city.startsWith(n) -> 3
            name.split(' ', '-', '/').any { it.startsWith(n) } || city.split(' ', '-').any { it.startsWith(n) } -> 4
            name.contains(n) || city.contains(n) -> 5
            else -> null
        }
    }

    private fun size(type: String) = when (type) {
        "large_airport" -> 0
        "medium_airport" -> 1
        else -> 2
    }
}

/** A route flown before, for the picker's "Recent Routes". */
data class RecentRoute(val origin: String, val destination: String, val date: Instant)

object RecentRoutes {
    /**
     * The last ten distinct routes, newest first, optionally only those
     * through an airport whose code contains [needle]. Port of
     * `AirportPickerView.recentRoutes`.
     */
    fun from(flights: List<Leg>, needle: String = "", limit: Int = 10): List<RecentRoute> {
        val n = needle.trim().uppercase()
        return flights
            .filter { it.origin.isNotEmpty() && it.destination.isNotEmpty() }
            .sortedByDescending { it.departure }
            .filter { n.isEmpty() || it.origin.contains(n) || it.destination.contains(n) }
            .distinctBy { it.origin to it.destination }
            .take(limit)
            .map { RecentRoute(it.origin, it.destination, it.departure) }
    }
}

/**
 * The airport time zone table shipped as `airport_timezones.csv`, one
 * `ICAO,Area/City` per line, generated by `scripts/airport_timezones.py`.
 */
object AirportTimezones {
    fun parse(csv: String): Map<String, String> =
        csv.lineSequence()
            .mapNotNull { line ->
                val comma = line.indexOf(',')
                if (comma <= 0) null else line.substring(0, comma).trim() to line.substring(comma + 1).trim()
            }
            .filter { it.second.isNotEmpty() }
            .toMap()
}
